export const nameMap = {
  "/": "Login",
  "/register": "Register",
  "/lupa-password": "Lupa Password",
  "/dashboard": "Dashbord",
  "/sale": "Sales",
  "/revenue": "Revenue",
  "/landing-page": "Landing Page",
  "/manage-asset-video": "Manage Asset Video",
  "/manage-asset-video/add": "Add New Video",
  "/manage-asset-video/edit/:id": "Edit Video",
  "/manage-asset-image": "Manage Asset Image",
  "/manage-asset-image/add": "Add New Image",
  "/manage-asset-image/edit/:id": "Edit Image",
  "/manage-asset-dataset": "Manage Asset Dataset",
  "/manage-asset-dataset/add": "Add New Dataset",
  "/manage-asset-dataset/edit/:id": "Edit Dataset",
  "/manage-asset-2D": "Manage Asset 2D",
  "/manage-asset-2D/add": "Add New Asset 2D",
  "/manage-asset-2D/edit/:id": "Edit Asset 2D",
  "/manage-asset-3D": "Manage Asset 3D",
  "/manage-asset-3D/add": "Add New Asset 3D",
  "/manage-asset-3D/edit/:id": "Edit Asset 3D",
  "/manage-asset-audio": "Manage Asset Audio",
  "/manage-asset-audio/add": "Add New Audio",
  "/manage-asset-audio/edit/:id": "Edit Audio",
  "/paymentSetting": "No.Rekening",
  "/user-revenue": "User Revenue",
  "/manage-users": "Manage Users",
  "/manage-users/add": "Add New User",
  "/manage-users/edit/:id": "Edit User",
  "/manage-admin": "Manage Admin",
  "/manage-admin/add": "Add New Admin",
  "/manage-admin/edit/:id": "Edit Admin",
  "*": "Error Page 404",
};
